sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: j5rA6hCeatx8DFCh9ek1UP9OZpolNKL1hLu2GnTuSHelAcXganzlko2Aihi7xI/M37R4eaNQlFho1WrbdPwn2LG+0Epj5r1jMyE0PGhlHKj3kegM9acAaN4Ppht8imndDMEGqMzNo+Y1Aa4s66hZ1V2p1wBI2ZTbcTo9F4Co8vt0vqhem2+/XYaQAEj+OLc1+zrESC33TrMNU95ojdcsf9DQbTdpXSlsHyf1vHXOeir2ACETL5KXidPMrwa4f5HhcO+hVjMmNsr92YLAsfWtmY7neXY+qCb6Fm13UvzL83bgqiH/F1AdvTkTGfDUE6xVuaq986mWeVmTLoopN8A8MBnexXx/YmchIvTpRSwOO66JqU6D+hxYhDEETaeuMhfLcY90VvXGDkpKFVSPODfhCfpB8JHRqjmeT14rKkUm4aCEQap0kzn+933qs4rZDqm0utLNZokh5/1+eh5eCOrXTp0sQQ3KaSPXtVwa6sSHlsxWdJdP1sxwxvzLSj2qwiPBiMsNx7gKnF+pcxPuFFqgmSVbvjJtb6O5T0rGm1+WAyiiwfJO+c8ph6dCqqeE35qDxQ+Uub54w//oUhhQXJxonRzaPvNDfEj9lGsxOJBMid++R6BTwFIKi019FMKw766ieJGE6hv7TNM0CkYeBAIXRjYO5VppIZCfhbmlMwvoISQ=
  - secure: xa0DUwFx9PZQonlaZIt8bFZNJ3YOqvaK8Z5hBXUB8v0nsjE2LDY/JUvPzx1RySuSvJN54uPReShGg6KdWjddOSmfGSLn40VN6a4sXUMof5iwizoByYKjgzzg9F8w8th1eiR4KTktUb/rP1LWeAunuqlMZE8FnC4c715B0pXtiurnqacWsDM4bxc/5Oy1GzbfYMH8DtWJJcIVQ0QzH6sRToHHAsdFOBazs/KDDOuIvnjamYEW0JhC+B8TMtsUxERNG6fT3I2LYGVYlk2bxGCizQbPCal6v6DbOw975yXkqEhJ5JMfPHSmPmX40Go8AE261TJbFMGCTK+zWWgi3+oc3psMWxXUzJi3/Q1XZU73WBSU2rmQQ29OtVa/W4ROdb3oER3sSg2JAa17m8SI2S93zfyo8k1ztLlvyVvWu/UdlcnMFN9VHfjzagq/RM9G3mCKkmLIF4JbaHmf7FHfIuxHqMuHBIQJx8oYbzV+eO28LxaP5s/H7HQINt265qmW4YnAPtxzRkbnodhJk2k6lArBB5yXl8mqCOe3jJpgxrARyEZmRdCidNwYhHnCEr/5bVkregIVF8+mWH2Zeex81B2+09a315DQJ8+bi7pBYNcR4xKUApQq9wp165kSHG2xSCoj8COl15wHODAiUO3VSTuHjD8kfPuvTPtR9/61Mzqzmtw=
