sudo: false
dist: trusty
language: node_js
node_js:
- lts/*
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: j5rA6hCeatx8DFCh9ek1UP9OZpolNKL1hLu2GnTuSHelAcXganzlko2Aihi7xI/M37R4eaNQlFho1WrbdPwn2LG+0Epj5r1jMyE0PGhlHKj3kegM9acAaN4Ppht8imndDMEGqMzNo+Y1Aa4s66hZ1V2p1wBI2ZTbcTo9F4Co8vt0vqhem2+/XYaQAEj+OLc1+zrESC33TrMNU95ojdcsf9DQbTdpXSlsHyf1vHXOeir2ACETL5KXidPMrwa4f5HhcO+hVjMmNsr92YLAsfWtmY7neXY+qCb6Fm13UvzL83bgqiH/F1AdvTkTGfDUE6xVuaq986mWeVmTLoopN8A8MBnexXx/YmchIvTpRSwOO66JqU6D+hxYhDEETaeuMhfLcY90VvXGDkpKFVSPODfhCfpB8JHRqjmeT14rKkUm4aCEQap0kzn+933qs4rZDqm0utLNZokh5/1+eh5eCOrXTp0sQQ3KaSPXtVwa6sSHlsxWdJdP1sxwxvzLSj2qwiPBiMsNx7gKnF+pcxPuFFqgmSVbvjJtb6O5T0rGm1+WAyiiwfJO+c8ph6dCqqeE35qDxQ+Uub54w//oUhhQXJxonRzaPvNDfEj9lGsxOJBMid++R6BTwFIKi019FMKw766ieJGE6hv7TNM0CkYeBAIXRjYO5VppIZCfhbmlMwvoISQ=
  - secure: xa0DUwFx9PZQonlaZIt8bFZNJ3YOqvaK8Z5hBXUB8v0nsjE2LDY/JUvPzx1RySuSvJN54uPReShGg6KdWjddOSmfGSLn40VN6a4sXUMof5iwizoByYKjgzzg9F8w8th1eiR4KTktUb/rP1LWeAunuqlMZE8FnC4c715B0pXtiurnqacWsDM4bxc/5Oy1GzbfYMH8DtWJJcIVQ0QzH6sRToHHAsdFOBazs/KDDOuIvnjamYEW0JhC+B8TMtsUxERNG6fT3I2LYGVYlk2bxGCizQbPCal6v6DbOw975yXkqEhJ5JMfPHSmPmX40Go8AE261TJbFMGCTK+zWWgi3+oc3psMWxXUzJi3/Q1XZU73WBSU2rmQQ29OtVa/W4ROdb3oER3sSg2JAa17m8SI2S93zfyo8k1ztLlvyVvWu/UdlcnMFN9VHfjzagq/RM9G3mCKkmLIF4JbaHmf7FHfIuxHqMuHBIQJx8oYbzV+eO28LxaP5s/H7HQINt265qmW4YnAPtxzRkbnodhJk2k6lArBB5yXl8mqCOe3jJpgxrARyEZmRdCidNwYhHnCEr/5bVkregIVF8+mWH2Zeex81B2+09a315DQJ8+bi7pBYNcR4xKUApQq9wp165kSHG2xSCoj8COl15wHODAiUO3VSTuHjD8kfPuvTPtR9/61Mzqzmtw=
  - secure: UHq+C/ulyFJ44Xv8SQEDui/SG8ZDmigZofIqAR6KAJyrgHLEN8ViQFzkQhVpTEiTEHxEC2sj+dg6ualbuk9AG8HduxQaEptzR+5uGzmkjngpM/U0U4u6/5UWz9ig0kuacI/EgSOxqrLhf3f0EM0o/f3NerzoniCiPdoP1Xm7eVUWk2TjGzBFWp2r65KL9fXePTcah/7n3Xm232ECTZ4sx1FZI+goR9PKooDHUVxMuzZ+twalCuvE+4CfoeZGRJrJRQdodVJnHps2kyf2JeXhUZvWK8kEE2SInmuoD6ZvJTatc58LYr2ie1f1/vFhcbQ7TycfQjdgjeo5J0SgPjBrlM3kWATka5i6dMrS1ruin5MU5t6ZIPveaWTmDWBgLReTO70GMyC9YyP0e9fULBu01i91+LA8cZ3bKfEGGXfalrdp7y9I9MJH79LyxgOc01C0lNgvp+5OVeDVdC2EsHQB0f9A8r1unF4sdT0IIBTUR9Gg+A531DMVrGY27rzBrKyW9mvJqQZfFx1bKV7eF4eLzYNZjQjJjHe5pLidNKSsvPwAxv19nv67i9ugeR0vCXhuW4zbw48zQsKqvIjsOm6MbMBCBFwcjq36F5uGB7W3O9xXdfY4Dtm1UYEOXY3F5ziPR6wlyYtUIZjjxmvFkExhzlpIoC8KowWA4Z1Jieg80Kw=
  - secure: WSs+psRxOq3cXq2BLW79lLM63vGNP4Q0mb95nmfv4AxFFNLQqJk157ka6PM9hsKAvv61a6j12TNvm/HACpe0yDp+jRHCvclreOzPuZG3AkkcPqiw7Ofzkz4fxAazw4StxM8z4o2MlMMxwigx9TCevfMwi2dkht2PAL7h7srZogFrjfjocgrsW5aQo1Z8t6v02KTq/c3D8XXobU8rDjI9cR2q0x1dcjhNvHUz1X7BPe5ZadfRrVGW5RXPnyGUCqk4VuNJ6Q9Yky5i/f9N9w7kdEZnRtvWlmee8nqdbcZ0xoJvdoly5RkByrxe1zhPXRYnu4fyjUAadWQz6Sp0wuA9SmTMjHOu4fddcnAKoDWD1F4syQKtNEtsbPEhHcw2/ZFxhgA9lg20+Ize6mNJyhLNOlxtVtaXIzJFD+8cmBRE2PaSuQuAHdZqV5hclHuNGP5abvEzFLWLuYlkKyZclwg+VbquFUi/37gXeF/nZ2vxKRvzzEMFWftipuygHWWCJC60wlSp4MxVIe8e46Sx/Q+JdLjG3cVluJQQTBo4YGLNLzCE6bYJBmGOExEzK4e/fMg4DTnum7DdMZugGaV9rQJP/8j/gLdaNBx6O92hS6ytauV016/gZaKCthTPYRXUrMj/fio9Y7voQTaZzh7XLT91niFcvI8SVfa7niYxEVjq/nQ=
